apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: https-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      conatiners:
      - name: https-echo
        image: jxlwqq/http-echo
        args: ["-text", "hello-world"]
        ports:
        - containerport: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
spec:
  ports:
  - ports: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    app: http-echo


